# fly.toml app configuration file generated for wispy-dust-8702 on 2023-07-20T02:48:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wispy-dust-8702"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
